= Cluster AGM: Trabajo Practico 2 - Programación III
:hardbreaks:
:title-page:
:numbered:
:source-highlighter: coderay
:tabsize: 4

Autores:Aldana Micaela Filiberto <Aldana.filiberto17@gmail.com>; Juliana Camila Nuñez <julicamila14@gmail.com>;
Docentes: Javier Marenco, Patricia Bagnes (Com-01);
 v1, {docdate}.


== Introducción:
El objetivo del trabajo práctico es implementar una aplicación para realizar clustering utilizando el algoritmo propuesto por Charles Zahn en el artíıculo “Graph-theoretical methods
for detecting and describing clusters” (IEEE Transactions on Computers 20-1, 1971). Dado
un conjunto de puntos en el plano y un grafo completo con estos puntos y con pesos en las
aristas iguales a la distancia euclídea entre los vértices, el algoritmo es el siguiente:
1. Calcular un árbol generador m´ınimo del grafo.
2. Eliminar del árbol las aristas cuyos pesos sean mayores que los pesos de sus aristas
vecinas.
El paso 2 del algoritmo se puede repetir hasta obtener una cantidad predeterminada de
clusters, o bien hasta que no haya aristas con peso significativamente distinto de sus aristas
vecinas. Implementar una interfaz visual para mostrar los puntos de la instancia, ejecutar el
algoritmo y mostrar sus resultados.
